create table category_table (
    id integer generated by default as identity primary key,
    name varchar(70) unique not null,
    date_time_created timestamp not null,
    date_time_updated timestamp
);


create table joke_table (
    id integer generated by default as identity primary key,
    description text not null,
    date_time_created timestamp not null,
    date_time_updated timestamp,
    category_id integer not null,
    constraint fk_category foreign key (category_id) references category_table
);