create table user_table(
    id integer generated by default as identity primary key,
    username varchar(50) unique not null,
    password varchar(80) not null,
    email varchar(255) unique not null,
    enabled boolean default false not null,
    date_time_created timestamp not null
);

create table authority_table(
    id integer generated by default as identity primary key,
    name varchar(50) unique not null
);

create table user_authority_table(
    user_id integer not null,
    authority_id integer not null,
    constraint fk_user foreign key (user_id) references user_table,
    constraint fk_authority foreign key (authority_id) references authority_table
);

create table category_table (
    id integer generated by default as identity primary key,
    name varchar(70) unique not null,
    date_time_created timestamp not null,
    date_time_updated timestamp
);

create table joke_table (
    id integer generated by default as identity primary key,
    description text not null,
    date_time_created timestamp not null,
    date_time_updated timestamp,
    category_id integer not null,
    user_id integer not null,
    constraint fk_category foreign key (category_id) references category_table,
    constraint fk_user foreign key (user_id) references user_table
);

alter sequence authority_table_id_seq RESTART WITH 1;
alter sequence user_table_id_seq RESTART WITH 1;
alter sequence category_table_id_seq RESTART WITH 1;
alter sequence joke_table_id_seq RESTART WITH 1;