create table category_table (
    id integer generated by default as identity primary key,
    title varchar(70) unique not null,
    date_time_created timestamp not null,
    date_time_updated timestamp
);


create table joke_table (
    id integer generated by default as identity primary key,
    description text not null,
    date_time_created timestamp not null,
    date_time_updated timestamp,
    category_id integer not null,
    constraint fk_category foreign key (category_id) references category_table
);

alter sequence category_table_id_seq RESTART WITH 1;
alter sequence joke_table_id_seq RESTART WITH 1;