create table verification_table(
    id integer generated by default as identity primary key,
    token varchar(255) unique not null,
    verified boolean default false not null,
    user_id integer not null,
    date_expiry date not null,
    date_time_created timestamp not null,
    constraint fk_user foreign key (user_id) references user_table
);

alter sequence verification_table_id_seq RESTART WITH 1;