create table comment_table(
    id integer generated by default as identity primary key,
    description text not null,
    parent_id integer,
    joke_id integer not null,
    user_id integer not null,
    date_time_created timestamp not null,
    constraint fk_parent foreign key (parent_id) references comment_table,
    constraint fk_joke foreign key (joke_id) references joke_table,
    constraint fk_user foreign key (user_id) references user_table
)