spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jokeAppDB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: post
    initialization-mode: always

  flyway:
    baseline-on-migrate: true

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org:
      springframework:
        web: DEBUG

server:
  port: 8090
